### ISSUE TITLE
Refine functionality of Course Base parser

### ISSUE THREAD

**Issue by andersfischernielsen** [simongray/ITUCourses#3]
# TODO
- Parse only from Fall 2005 to Spring 2014
- Parse the time of lectures
- Parse the room of the course
- Parse to dictionaries
- Parse room/timeslot

**Comment by simongray** [comment]
Let's see if we can get data in the format of

``` python
[
   {
      'course': 'Introduction to blabla',
      'timeslot': 'xxxxx',
      ...
   } 
]
```
